### ISSUE TITLE
Zookeeper error when run Blueflood

### ISSUE THREAD

**Issue by ebereketoglu** [rackerlabs/blueflood#459]
I am trying to run blueflood-all.jar with the following configurations

log4j.properties:
```
log4j.appender.console.additionalFields={'environment': 'dev', 'application': 'bf', 'instance_id': '0'}
log4j.appender.console.extractStacktrace=true
log4j.appender.console.addExtendedInformation=true
log4j.appender.console.facilityIsLogger=true
log4j.appender.console.layout=org.apache.log4j.PatternLayout

log4j.logger.httpclient.wire.header=WARN
log4j.logger.httpclient.wire.content=WARN

log4j.category.org.apache.zookeeper.ClientCnxn=WARN
log4j.category.org.apache.zookeeper.client.ZooKeeperSaslClient=ERROR

log4j.logger.org.apache.http.client.protocol=INFO
log4j.logger.org.apache.http.wire=INFO
log4j.logger.org.apache.http.impl=INFO
log4j.logger.org.apache.http.headers=INFO

log4j.rootLogger=INFO, console
```
```
java -cp /home/ubuntu/blueflood/blueflood-all/target/blueflood-all-2.0.0-SNAPSHOT-jar-with-dependencies.jar \
-Dblueflood.config=file:///home/ubuntu/blueflood/blueflood-core/src/main/resources/configDefaults/blueflood.properties \
-Dlog4j.configuration=file:///home/ubuntu/blueflood/blueflood-core/log4j.properties \
com.rackspacecloud.blueflood.service.BluefloodServiceStarter
```

But I am getting these errors:
```
log4j:ERROR Could not find value for key log4j.appender.console
log4j:ERROR Could not instantiate appender named "console".
log4j:ERROR Could not find value for key log4j.appender.console
log4j:ERROR Could not instantiate appender named "console".

```

**Comment by pkit** [comment]
Define the appender?

    log4j.appender.console=org.apache.log4j.ConsoleAppender

**Comment by ebereketoglu** [comment]
Thanks, I defined the appender and this error has been solved but at this time I am getting Zookeeper error. 

```
 com.rackspacecloud.blueflood.service.BluefloodServiceStarter
log4j:WARN No such property [addExtendedInformation] in org.apache.log4j.ConsoleAppender.
log4j:WARN No such property [facilityIsLogger] in org.apache.log4j.ConsoleAppender.
log4j:WARN No such property [additionalFields] in org.apache.log4j.ConsoleAppender.
log4j:WARN No such property [extractStacktrace] in org.apache.log4j.ConsoleAppender.
log4j:WARN No such property [addExtendedInformation] in org.apache.log4j.ConsoleAppender.
log4j:WARN No such property [facilityIsLogger] in org.apache.log4j.ConsoleAppender.
log4j:WARN No such property [additionalFields] in org.apache.log4j.ConsoleAppender.
log4j:WARN No such property [extractStacktrace] in org.apache.log4j.ConsoleAppender.
Starting
Client environment:zookeeper.version=3.4.5-1392090, built on 09/30/2012 17:52 GMT
Client environment:host.name=ip-172-30-0-249.ec2.internal
Client environment:java.version=1.7.0_76
Client environment:java.vendor=Oracle Corporation
Client environment:java.home=/usr/lib/jvm/java-7-oracle/jre
Client environment:java.class.path=/home/ubuntu/blueflood/blueflood-all/target/blueflood-all-2.0.0-SNAPSHOT-jar-with-dependencies.jar
Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
Client environment:java.io.tmpdir=/tmp
Client environment:java.compiler=<NA>
Client environment:os.name=Linux
Client environment:os.arch=amd64
Client environment:os.version=3.13.0-48-generic
Client environment:user.name=ubuntu
Client environment:user.home=/home/ubuntu
Client environment:user.dir=/home/ubuntu
Initiating client connection, connectString=127.0.0.1:22181 sessionTimeout=120000 watcher=org.apache.curator.ConnectionState@4d56d418
Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
Cannot connect to Zookeeper; will not perform initial lock acquisition
Starting blueflood services
Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=MyConnectionPool,ServiceType=connectionpool
AddHost: 127.0.0.1
Shard push and pull services started
Ingestion mode is enabled, however no ingestion modules are enabled!
```

**Comment by pkit** [comment]
As you can see it's "Connection refused" to "127.0.0.1:22181"
Probably zookeeper is not running.

**Comment by GeorgeJahad** [comment]
From the 10 minute guide:
https://github.com/rackerlabs/blueflood/wiki/10minuteguide
 "It is recommended to set to NONE until you need Zookeeper to coordinate rollup slaves."

**Comment by GeorgeJahad** [comment]
Sorry the complete quote is:
ZOO_KEEPER_CLUSTER: A comma delimited list of host:port tuples. It is recommended to set to NONE until you need Zookeeper to coordinate rollup slaves.

**Comment by ebereketoglu** [comment]
Yes, I have missed that part, thank you.
