### ISSUE TITLE
Compatibility with Java 8

### ISSUE THREAD

**Issue by menchauser** [rackerlabs/blueflood#504]
Are there any plans to make BlueFlood ready for Java 8? The main reason for that decision could be that Java 7 [is not supported since April 2015](https://www.java.com/en/download/faq/java_7.xml). 
Currently it is impossible to build BlueFlood with JDK 8 because of the **blueflood-core** module's failing test:

```
Running com.rackspacecloud.blueflood.io.serializers.IMetricSerializerTest
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.79 sec <<< FAILURE!
testSetSerialization(com.rackspacecloud.blueflood.io.serializers.IMetricSerializerTest)  Time elapsed: 1.24 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<..."count":9,"hashes":[[746007989,1875251108,98262,103159993,1727114331,-1034140067,98699,1062516268,99644]]}> but was:<..."count":9,"hashes":[[-1034140067,746007989,1875251108,98262,1062516268,1727114331,98699,99644,103159993]]}>
        at junit.framework.Assert.assertEquals(Assert.java:85)
        at junit.framework.Assert.assertEquals(Assert.java:91)
        at com.rackspacecloud.blueflood.io.serializers.IMetricSerializerTest.testSetSerialization(IMetricSerializerTest.java:76)
```

Also BlueFlood built with JDK 7 throws an exception during start under JVM 8:

```
2015-08-14 14:56:39 INFO  efloodServiceStarter:302 - Starting blueflood services
2015-08-14 14:56:39 INFO  tionPoolMBeanManager:45  - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=MyConnectionPool,ServiceType=connectionpool
2015-08-14 14:56:39 INFO  onnectionPoolMonitor:239 - AddHost: 127.0.0.1
2015-08-14 14:56:40 INFO  efloodServiceStarter:76  - Shard push and pull services started
2015-08-14 14:56:40 INFO  efloodServiceStarter:98  - Loading ingestion service module com.rackspacecloud.blueflood.service.HttpIngestionService
2015-08-14 14:56:40 INFO  efloodServiceStarter:106 - Starting ingestion service module com.rackspacecloud.blueflood.service.HttpIngestionService with writer: AstyanaxMetricsWriter
2015-08-14 14:56:40 ERROR Instrumentation     :60  - Unable to register mbean for Instrumentation
javax.management.NotCompliantMBeanException: Interface is not public: com.rackspacecloud.blueflood.io.InstrumentationMBean
        at com.sun.jmx.mbeanserver.MBeanAnalyzer.<init>(MBeanAnalyzer.java:114)
        at com.sun.jmx.mbeanserver.MBeanAnalyzer.analyzer(MBeanAnalyzer.java:102)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.getAnalyzer(StandardMBeanIntrospector.java:67)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.getPerInterface(MBeanIntrospector.java:192)
        at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:138)
        at com.sun.jmx.mbeanserver.StandardMBeanSupport.<init>(StandardMBeanSupport.java:60)
        at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:192)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at com.rackspacecloud.blueflood.io.Instrumentation.<clinit>(Instrumentation.java:58)
        at com.rackspacecloud.blueflood.io.AstyanaxReader.getShardState(AstyanaxReader.java:198)
        at com.rackspacecloud.blueflood.io.AstyanaxShardStateIO.getShardState(AstyanaxShardStateIO.java:19)
        at com.rackspacecloud.blueflood.service.ShardStatePuller.performOperation(ShardStatePuller.java:42)
        at com.rackspacecloud.blueflood.service.ShardStateWorker.run(ShardStateWorker.java:88)
        at java.lang.Thread.run(Thread.java:745)
2015-08-14 14:56:40 INFO  tricsIngestionServer:103 - Starting metrics listener HTTP server on port 19000
2015-08-14 14:56:40 INFO  tricsIngestionServer:112 - Starting tracker service
2015-08-14 14:56:40 INFO  efloodServiceStarter:109 - Successfully started ingestion service module com.rackspacecloud.blueflood.service.HttpIngestionService with writer: AstyanaxMetricsWriter
2015-08-14 14:56:40 INFO  efloodServiceStarter:128 - Started 1 ingestion services
2015-08-14 14:56:40 INFO  efloodServiceStarter:147 - Loading query service module com.rackspacecloud.blueflood.service.HttpQueryService
2015-08-14 14:56:40 INFO  efloodServiceStarter:152 - Starting query service module com.rackspacecloud.blueflood.service.HttpQueryService
2015-08-14 14:56:40 INFO  etricDataQueryServer:73  - Starting metric data query server (HTTP) on port 20000
2015-08-14 14:56:40 INFO  efloodServiceStarter:154 - Successfully started query service module com.rackspacecloud.blueflood.service.HttpQueryService
2015-08-14 14:56:40 INFO  efloodServiceStarter:173 - Started 1 query services
2015-08-14 14:56:40 INFO  efloodServiceStarter:240 - No event listener modules configured.
2015-08-14 14:56:40 INFO  efloodServiceStarter:308 - All blueflood services started
```

My environment: 
- Ubuntu 14.04
- Maven 3.0.5
- Java 7 build: 1.7.0u80
- Java 8 build: 1.8.0u51

**Comment by atlanssia** [comment]
* About the failing test:  As of BluefloodSetRollup.class use HashSet which does not guarantee that the order will remain constant over time, I skipped this test case in our project.

* About InstrumentationMBean: I declared this interface in a new file named `InstrumentationMBean.java`

hope it helpful

**Comment by stackedsax** [comment]
@menchauser yes, we've been working to update everything to work with Java 8.  @shintasmith was looking into the tests, specifically.

@atlanssia would you like to submit a PR for the IntstrumentationMBean.java problem?

**Comment by shintasmith** [comment]
@atlanssia that IMetricSerializerTest compare error should be fixed in this PR: https://github.com/rackerlabs/blueflood/pull/553 . I did run Blueflood built with JDK 1.8, was able to do simple ingest and query.

**Comment by shintasmith** [comment]
@menchauser , since https://github.com/rackerlabs/blueflood/releases/tag/blueflood-2.0.0 , JDK8 is the only supported JDK for blueflood.

**Comment by shintasmith** [comment]
Closing this
